

services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend  # Points to the frontend directory
      dockerfile: Dockerfile
    ports:
      - "80:80"  # React app will be served on port 80
    networks:
      - polling-net
    depends_on:
      - backend  # Ensures frontend starts only after backend is up

  # Backend Service
  backend:
    build:
      context: ./backend  # Points to the backend directory
      dockerfile: Dockerfile
    environment:
      - DB_URI=mongodb://database:27017/pollingApp
      - PORT=5000
    ports:
      - "5000:5000"  # Backend API accessible on port 5000
    networks:
      - polling-net
    depends_on:
      - database  # Ensures backend waits for database to start

  # MongoDB Service
  database:
    image: mongo:latest  # Using the latest official MongoDB image
    volumes:
      - mongodb_data:/data/db  # Persist MongoDB data
    networks:
      - polling-net
    ports:
      - "27017:27017"  # MongoDB exposed on port 27017 for the backend to connect

networks:
  polling-net:  # Create a custom network for inter-service communication

volumes:
  mongodb_data:  # Persist MongoDB data
